GET http://localhost:4000/auth HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNhZTFmOGFlNTkwNzU5M2RkYmE1NWYiLCJ1c2VybmFtZSI6InpTb3JvdXIiLCJpYXQiOjE2NDA3MTkzMzYsImV4cCI6MTY0MDcyMjkzNn0.w4qV9XcITcpJGAuu89nFUwbIPP0ZQoZEPAwJ86PscsU 