GET http://localhost:4000/auth HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWQwMmVjOWZlMGU0M2Q4NWY5ODM2YTMiLCJ1c2VybmFtZSI6InpTb3JvdXI3NyIsImlhdCI6MTY0MTAzMzY4OSwiZXhwIjoxNjQxMDM3Mjg5fQ.efum9xazImof8VJVbHMS1U8hYFQEgUinjflHeB3HcD4